### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by hsgonzalmu** [jbkunst/profesor-labarca-website#1]

**Comment by hsgonzalmu** [comment]
Noticias categorizadas con la opción de poder comentarlas

**Comment by jbkunst** [comment]
Si tienes un blog o una página web, las imágenes son un recurso necesario e imprescindible para conseguir mantener la atención del público y evitar aburrirlos.

Además, usar imágenes mejora sensiblemente la estética del sitio y tiene beneficios colaterales que no son nada obvios, pero muy importantes como, por ejemplo, el hecho de mejorar el posicionamiento de la página si se saben utilizar el potencial que las imágenes tienen para el SEO
