### ISSUE TITLE
Otras categorias para el menu/blog

### ISSUE THREAD

**Issue by hsgonzalmu** [jbkunst/profesor-labarca-website#10]
El profesor dice: "Agregaría una para opiniones sobre diversos temas relativos a mi quehacer". Entiendo que debería ser un blog sobre diversos temas. ¿Qué opinas?

**Comment by jbkunst** [comment]
Creo que por default todo debe ir en un blog, por ejemplo en un "diario" hay muchas noticias/escritos de diversos temas, solamente se categorizan.

Otra cosa, si puedes poner títulos más descriptivos ;)!

Última cosa, tu avatar es una piscola?

**Comment by hsgonzalmu** [comment]
Estoy de acuerdo con tu comentario.
Si, es una piscola
